/* -*- mode: c; mode: font-lock; fill-column: 75; comment-column: 50; */
/* $Id$ */

#include <stdio.h>

main ()
{
  FILE *fp;
  union {
    unsigned int ui;
    char byte[4];
  } i;

  fp = fopen ("swap.h", "w");

  fprintf (fp, "/* header file generated by endian.c -- do not edit */\n\n");

  i.ui = 0;
  i.byte[3]= 1;

  if (i.ui == 1) {
    fprintf (stderr, "big endian [%u]\n", i.ui); 
    fprintf (fp, "/* big endian [%u] */\n", i.ui); 
    fprintf (fp, "#define DOSWAP 0\n");
  }
  else {
    fprintf (stderr, "little endian [%u]\n", i.ui); 
    fprintf (fp, "/* little endian [%u] */\n", i.ui); 
    fprintf (fp, "#define DOSWAP 1\n");
  }
  fclose(fp);
  fprintf (stderr, "swap.h generated\n");
}

